title: Vineeth Guptha
logo: 20231013_122959.jpg
description: A Data Scientist with 4 years of experience in solving business and research problems by applying Machine Learning, Deep Learning, and Natural Language Processing algorithms. Currently pursuing a Masters in Data Science at the University of San Francisco.
theme: jekyll-theme-minimal
