title:    Vineeth Guptha
logo: 20231013_122959-modified.png
description: <a href="https://www.linkedin.com/in/vineethguptha/"> Connect with me on LinkedIn </a>
show_downloads: true
theme: jekyll-theme-minimal
