title: Vineeth Guptha
logo: 20231013_122959-modified.png
description: A Data Scientist with 4 years of experience in solving business and research problems by applying Machine Learning, Deep Learning, and Natural Language Processing algorithms.
contact: vineeth.guptha@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
