title:    Vineeth Guptha
logo: 20231013_122959-modified.png
description: <a href="https://www.linkedin.com/in/vineethguptha/"> LinkedIn: linkedin.com\in\vineethguptha </a>
show_downloads: true
theme: jekyll-theme-minimal
